<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?>

<div class="PrivacyPnl">
  <div class="container">
    <h2>Terms & Condition</h2>
    <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.</p>
    <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</p>
    <h4>What is Lorem Ipsum?</h4>
    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.</p>
    <p>All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words.</p>
    <h4>Where can I get some?</h4>
    <p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>
    <p>Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur.</p>
    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.</p>
    <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.</p>
    <h4>Agreement</h4>
    <ul>
      <li> You agree that: </li>
      <li> the personal information that you provide when you register is true and accurate, you are not impersonating any other person or entity. </li>
      <li> The products purchased on this site are for private and domestic use only and are not for re sale. Failure to comply will result in the termination of your subscription and your account being blocked. </li>
      <li> You will inform us of any changes to your personal information on your account by e-mailing or calling our customer service team. </li>
      <li> Access to this Website is permitted on a temporary basis, and we reserve the right to withdraw or amend the Services without notice. We will not be liable if for any reason this Website is unavailable at any time. Occasionally, we may restrict access to some parts or this entire Website. </li>
      <li> This Website occasionally contains links to other websites, which are not operated by SS (the "Linked Sites"). SS has no control over the Linked Sites and accepts no responsibility for them or for any loss or damage that may arise from your use of them. Your use of the Linked Sites will be subject to the terms of use and service contained within each site. </li>
      <li> SS is the data controller of this website for the purpose of the Data Protection Act 1998 ("The Act"). </li>
      <li> You have the right to access the information which SS holds about you and this right can be exercised in accordance with the Act. Any access request may be subject to a fee of £10 to meet our costs in providing you with details of the information we hold about you. </li>
    </ul>
    <h4>Monthly Membership</h4>
    <ul>
      <li> Your membership will commence when you place your first order for your first subscription box. </li>
      <li> Your first payment will consist of one month's membership/subscription fee, followed by a monthly payment of the same amount made on the same day/date each month thereafter. Monthly payments will begin one month after your initial payment and will remain valid until you cancel. </li>
      <li> We will charge you a monthly subscription fee (stated to you at the time of purchase) on your billing date every month until you cancel your membership. Once the monthly fee has been charged it is final and no refund is available. </li>
      <li> Your membership will automatically renew on the same date each month. </li>
      <li> If you forget/fail to make your selections within your 1-month window and before your next billing date – a surprise box is automatically sent out to cover the previous month's payment. You can view this surprise box order directly through your account. </li>
    </ul>
    <div class="para-service">
      <h4>Use of Our Service</h4>
      <p>We provide a place for you to stay up to date with current trends in beauty products and discover new niche brands.</p>
      <p><strong>A) Eligibility</strong><br>
        You may use the Service only if you can form a binding contract with Shade Sirch Limited., and only in compliance with this Agreement and all applicable laws, rules and regulations. Any use or access to the Service by anyone under 18 is strictly prohibited. The Service may not available to any Users previously removed from the Service by Shade Sirch Limited.</p>
      <p><strong>B) Shade Sirch Limited. Accounts and Ordering</strong><br>
        Your Shade Sirch Limited. customer account gives you the ability to order and purchase products listed on our site, and to have access to the services and functionality that we may establish and maintain from time to time and in our sole discretion. We may maintain different types of accounts for different types of Users. If you open a Shade Sirch Limited. account on behalf of a company, organization, or other entity, then (a) "you" includes you and that entity, and (b) you represent and warrant that you are an authorized representative of the entity with the authority to bind the entity to this Agreement, and that you agree to this Agreement on the entity's behalf. By connecting to Shade Sirch Limited. with a third-party service, such as a social media service, you give us permission to access and use your information from that service as permitted by that service, and to store your log-in credentials from that service. </p>
      <p>You may never use another User's account without permission. When creating your account, you must provide accurate and complete information. You are solely responsible for the activity that occurs on your account, and you must keep your account password secure. We encourage you to use "strong" passwords (passwords that use a combination of upper and lower case letters, numbers and symbols) with your account. You must notify Shade Sirch Limited. immediately of any breach of security or unauthorized use of your account. Shade Sirch Limited. will not be liable for any losses caused by any unauthorized use of your account.</p>
      <p>You may control your User profile and how you interact with the Service by changing the settings in your customer account page. By providing Shade Sirch Limited. your email address you consent to our using the email address to send you Service-related notices, including any notices required by law, in lieu of communication by postal mail. We may also use your email address to send you other messages, such as changes to features of the Service and special offers. If you do not want to receive such email messages, you may opt out or change your preferences in your customer account page. Opting out may prevent you from receiving email messages regarding updates, improvements, or offers.</p>
      <p><strong>C) Service Rules</strong><br>
        In order to use the Service, you agree not to engage in any of the following prohibited activities: (i) copying, distributing, or disclosing any part of the Service in any medium, including without limitation by any automated or non-automated "scraping"; (ii) using any automated system, including without limitation "robots," "spiders," "offline readers," etc., to access the Service in a manner that sends more request messages to the Shade Sirch Limited. servers than a human can reasonably produce in the same period of time by using a conventional on-line web browser (except that Shade Sirch Limited. grants the operators of public search engines revocable permission to use spiders to copy materials from our Site for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials); (iii) transmitting spam, chain letters, or other unsolicited email; (iv) attempting to interfere with, compromise the system integrity or security or decipher any transmissions to or from the servers running the Service; (v) taking any action that imposes, or may impose at our sole discretion an unreasonable or disproportionately large load on our infrastructure; (vi) uploading invalid data, viruses, worms, or other software agents through the Service; (vii) collecting or harvesting any personally identifiable information, including account names, from the Service; (viii) using the Service for any commercial solicitation purposes; (ix) impersonating another person or otherwise misrepresenting your affiliation with a person or entity, conducting fraud, hiding or attempting to hide your identity; (x) interfering with the proper working of the Service; (xi) accessing any content on the Service through any technology or means other than those provided or authorized by the Service; or (xii) bypassing the measures we may use to prevent or restrict access to the Service, including without limitation features that prevent or restrict use or copying of any content or enforce limitations on use of the Service or the content therein.</p>
      <p>You may copy and redistribute the audiovisual content available on the Service; however, you may not alter or modify such audiovisual content in any manner and you may not remove any copyrights associated with the such audiovisual content</p>
      <p>We may, without prior notice, change the Service; stop providing the Service or features of the Service, to you or to users generally; or create usage limits for the Service. We may permanently or temporarily terminate or suspend your access to the Service without notice and liability for any reason, including if in our sole determination you violate any provision of this Agreement, or for no reason. Upon termination for any reason or no reason, you continue to be bound by this Agreement.</p>
      <p>You are solely responsible for your interactions with other Shade Sirch Limited. Users. We reserve the right, but have no obligation, to monitor disputes between you and other Users. Shade Sirch Limited. shall have no liability for your interactions with other Users, or for any User's action or inaction.</p>
      <br>
      </p>
    </div>
  </div>
</div>